version: 0.0
os: linux
files:
  - source: deploy/
    destination: /home/ec2-user/deploy

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user