version: 0.0
os: linux
files:
  - source: deploy/
    destination: /home/ec2-user/deploy

hooks:
  BeforeInstall:
    - location: scripts/preScript.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/postScript.sh
      timeout: 60
      runas: ec2-user