version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - ./gradlew clean
  build:
    commands:
      - echo Building the application...
      - ./gradlew build -x test
  post_build:
    commands:
      - echo Build completed.
      - mkdir -p deploy
      - cp build/libs/*.jar deploy/

artifacts:
  files:
    - deploy/*.jar
    - appspec.yml
    - scripts/**